apiVersion: v2
name: sskd-infrastructure
description: Infrastructure chart (namespace, SSL, Traefik, Headlamp, PowerDNS)
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: headlamp
    version: "0.25.0"
    repository: https://kubernetes-sigs.github.io/headlamp/
    condition: headlamp.enabled