namespace: sskd

ssl:
  email: alhipce@mail.ru
  domain: sskd.tech
  cloudflare:
    email: ""
    apiToken: ""

headlamp:
  enabled: true
  service:
    type: NodePort
    port: 80
    nodePort: 30080
  clusterRoleBinding:
    create: true
    clusterRoleName: cluster-admin

powerdns:
  enabled: true
  apiKey: ""
  adminSecretKey: ""
  dnsNodePort: 30053
  webNodePort: 30081
  persistence:
    size: 1Gi
