namespace: sskd

ssl:
  email: alhipce@mail.ru
  domain: sskd.tech
  cloudflare:
    email: ""
    apiToken: ""

headlamp:
  enabled: true
  service:
    type: NodePort
    port: 80
    nodePort: 30080
  clusterRoleBinding:
    create: true
    clusterRoleName: cluster-admin

technitium-dnsserver:
  enabled: true
  service:
    dns:
      type: NodePort
      nodePort: 30053
    web:
      type: NodePort
      nodePort: 30081
  persistence:
    enabled: true
    size: 1Gi
