namespace: sskd

ssl:
  email: alhipce@mail.ru
  domain: sskd.tech
  cloudflare:
    email: ""
    apiToken: ""

headlamp:
  enabled: true
  service:
    type: NodePort
    port: 80
    nodePort: 30080
  clusterRoleBinding:
    create: true
    clusterRoleName: cluster-admin

pihole:
  enabled: true
  adminPassword: ""
  DNS1: "1.1.1.1"
  DNS2: "1.0.0.1"
  persistentVolumeClaim:
    enabled: true
    size: 1Gi
  serviceDns:
    mixedService: false
    type: NodePort
    port: 53
    nodePort: "30053"
  serviceWeb:
    type: NodePort
    http:
      enabled: true
      port: 80
      nodePort: "30081"
  podDnsConfig:
    enabled: true
    policy: "None"
    nameservers:
      - 127.0.0.1
      - 1.1.1.1
