app:
  name: my-app
  namespace: sskd
  replicas: 1
  port: 80
  healthPath: /

  hostNetwork: false

  nodeSelector: {}

  image:
    repository: ""
    tag: ""
    pullPolicy: Always

  env:
    NODE_ENV: production

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

  ingress:
    enabled: false
    # Вариант 1: Полный хост
    host: ""
    # Вариант 2: Только поддомен (автоматически добавит .sskd.tech)
    subdomain: ""
    path: /

  baseDomain: sskd.tech
  wildcardTls: true

  secrets:
    apiUrl:
      enabled: false
      envName: API_URL

  # Proxy на другие сервисы
  proxy: []
