# ================================================
# СКОПИРУЙТЕ И ИЗМЕНИТЕ 2 СТРОКИ!
# ================================================
name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      server:
        description: "Target server"
        required: false
        default: "1"
        type: choice
        options:
          - "1"
          - "2"

jobs:
  deploy:
    uses: etozhealkhipce/senior-script-kiddie-k3s/.github/workflows/deploy-app.yml@main
    with:
      app_name: my-app           # <-- ИЗМЕНИТЕ
      app_host: my-app.sskd.tech # <-- ИЗМЕНИТЕ (удалите если не нужен ingress)
      server: ${{ inputs.server || '1' }}
    secrets: inherit
