# ================================================
# СКОПИРУЙТЕ И ИЗМЕНИТЕ 2 СТРОКИ!
# ================================================
name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    uses: etozhealkhipce/senior-script-kiddie-k3s/.github/workflows/deploy-app.yml@main
    with:
      app_name: my-app           # <-- ИЗМЕНИТЕ
      app_host: my-app.sskd.tech # <-- ИЗМЕНИТЕ (удалите если не нужен ingress)
    secrets: inherit
