name: Deploy Infrastructure

on:
  push:
    branches: [main]
    paths:
      - "charts/sskd-infrastructure/**"
      - ".github/workflows/deploy-infrastructure.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy charts to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "charts/sskd-infrastructure/*"
          target: "/tmp/sskd-infra"

      - name: Deploy Infrastructure to K3s
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            cd /tmp/sskd-infra/charts/sskd-infrastructure

            helm upgrade --install sskd-infrastructure . --create-namespace

            echo "Done!"

            rm -rf /tmp/sskd-infra
