apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ssl
spec:
  acme:
    email: { { .Values.ssl.email } }
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: ssl
    solvers:
      - http01:
          ingress:
            class: traefik
